version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7890:7890"
    volumes:
      - .:/app
      - /app/node_modules 
    command: ["bun", "run", "dev"]
